<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--le dice a .NET que genere un archivo XML con todos los comentarios del codigo-->
    <!--swagger lee ese archivo para mostrar la documentacion de cada endpoint-->
    <!--sin esta linea swagger no puede leer los comentarios que vas a agregar en el Controller-->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--evita que Visual Studio muestre advertencias en los metodos que no tengan comentarios-->
    <!--sin esta linea aparecerian cientos de advertencias amarillas en todo el proyecto-->
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>

</Project>